repos:
  - repo: local
    hooks:

      - id: gen-decks-status
        name: Generate Decks Status Table
        entry: bash scripts/precommit_gen_decks_status.sh
        language: system
        files: '/info\.(yml|yaml)$|^scripts/gen_decks_status\.py$'
        stages: [commit]
        require_serial: true # otherwise multiple gits can interfere and choke on index.lock
