title: JPDB Game Decks
tagline: Open-source Japanese flash cards
description: An unofficial, open-source collection of Japanese language flash cards for jpdb.io, based entirely on video games.
url: "https://philipguin.github.io"
baseurl: "/JpdbGameDecks"

twitter_username: frizzildev
github_username: philipguin

remote_theme: jekyll/minima # no '@v2.5.1' because latest tag way behind HEAD
minima:
  skin: dark
  social_links:
    - { platform: github,  user_url: "https://github.com/philipguin/JpdbGameDecks" }
    - { platform: twitter, user_url: "https://twitter.com/frizzildev" }

plugins:
- jekyll-remote-theme